# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

right_format = "$cmd_duration"
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$vcsh\
$memory_usage\
$aws\
$gcloud\
${env_var.OCI_CLI_PROFILE}\
$openstack\
$azure\
$kubernetes\
$nix_shell\
$env_var\
$line_break\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
${custom.jj}\
$line_break\
$sudo\
$directory\
$direnv\
$jobs\
$time\
$status\
$package\
$shell\
$character"""

[cmd_duration]
format = "[$duration](dimmed)"
min_time = 2_000
show_milliseconds = true

[status]
disabled = false
symbol = "✖"

[git_metrics]
disabled = true

[git_status]
# using jj-starship
disabled = true

[git_commit]
# using jj-starship
disabled = true

[git_state]
# using jj-starship
disabled = true

[git_branch]
symbol = " "
format = "[$symbol$branch(:$remote_branch)]($style) "
# using jj-starship
disabled = true

[kubernetes]
disabled = false
style = "blue bold"
format = 'on [$symbol$context( \($namespace\))]($style) '
detect_folders = ['deploy']

# Nerd font replacements

[aws]
symbol = " "

[buf]
symbol = " "
disabled = true

[c]
symbol = " "
disabled = true

[conda]
symbol = " "
disabled = true

[dart]
symbol = " "
disabled = true

[directory]
truncation_symbol = "…/"
truncate_to_repo = false
read_only = " "

[direnv]
disabled = true
symbol = " "

[docker_context]
symbol = " "
disabled = true

[elixir]
symbol = " "
disabled = true

[elm]
symbol = " "
disabled = true

[gcloud]
symbol = " "
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
detect_env_vars = ["CLOUDSDK_ACTIVE_CONFIG_NAME"]

[golang]
symbol = " "
disabled = true

[haskell]
symbol = " "
disabled = true

[hg_branch]
symbol = " "

[java]
symbol = " "
disabled = true

[julia]
symbol = " "
disabled = true

[lua]
symbol = " "
disabled = true

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "
disabled = true

[nim]
symbol = " "
disabled = true

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
disabled = true

[package]
symbol = " "
disabled = true

[python]
symbol = " "
disabled = true

[rlang]
symbol = "ﳒ "
disabled = true

[ruby]
symbol = " "
disabled = true

[rust]
symbol = " "
disabled = true

[scala]
symbol = " "
disabled = true

[spack]
symbol = "🅢 "
disabled = true

# Plugins

[custom.jj]
command = "prompt"
format = "$output"
shell = ["jj-starship"]
when = "jj-starship detect"

[env_var.OCI_CLI_PROFILE]
symbol = " "
style = "bold #F0CC72"
format = "on [$symbol($env_value)]($style) "
