require("options")
require("keymaps")
require("colors")
require("highlight_yank")
require("disable_new_line_comment")
require("cursor_hold_highlight")
require("lazy-bootstrap")
require("lsp")

-- vim.lsp.set_log_level("trace")
